name: gh-pages-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: false

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages
        run: yarn install
      - name: Test code
        if: github.event_name == 'pull_request'
        run: yarn test:unit
      - name: Build app
        run: yarn build
      - name: Deploy to gh-pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: false
          publish_dir: ./dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
